// Dữ liệu sản phẩm – HUY MẬP STORE (Chuẩn gọn – chuyên nghiệp)
const products = [
  /* ================== NIKE (10) ================== */
  {
    id: 1,
    name: "Nike Air Jordan 1 High",
    category: "nike",
    price: 4500000,
    image: "./assets/images/nike/1.png",
  },
  {
    id: 2,
    name: "Nike Air Force 1",
    category: "nike",
    price: 2900000,
    image: "./assets/images/nike/2.png",
  },
  {
    id: 3,
    name: "Nike Dunk Low",
    category: "nike",
    price: 3200000,
    image: "./assets/images/nike/3.png",
  },
  {
    id: 4,
    name: "Nike Air Max 270",
    category: "nike",
    price: 3500000,
    image: "./assets/images/nike/4.png",
  },
  {
    id: 5,
    name: "Nike Air Max 97",
    category: "nike",
    price: 4100000,
    image: "./assets/images/nike/5.png",
  },
  {
    id: 6,
    name: "Nike Blazer Mid 77",
    category: "nike",
    price: 2800000,
    image: "./assets/images/nike/6.png",
  },
  {
    id: 7,
    name: "Nike Pegasus 40",
    category: "nike",
    price: 3300000,
    image: "./assets/images/nike/7.png",
  },
  {
    id: 8,
    name: "Nike Vapormax Plus",
    category: "nike",
    price: 4800000,
    image: "./assets/images/nike/8.png",
  },
  {
    id: 9,
    name: "Nike Jordan 1 Low",
    category: "nike",
    price: 3900000,
    image: "./assets/images/nike/9.png",
  },
  {
    id: 10,
    name: "Nike ZoomX Vaporfly",
    category: "nike",
    price: 6200000,
    image: "./assets/images/nike/10.png",
  },

  /* ================== ADIDAS (10) ================== */
  {
    id: 11,
    name: "Adidas Ultraboost 22",
    category: "adidas",
    price: 3800000,
    image: "./assets/images/adidas/1.png",
    qty: 0,
  },
  {
    id: 12,
    name: "Adidas Forum Low",
    category: "adidas",
    price: 2500000,
    image: "./assets/images/adidas/2.png",
  },
  {
    id: 13,
    name: "Adidas Samba OG",
    category: "adidas",
    price: 2700000,
    image: "./assets/images/adidas/3.png",
  },
  {
    id: 14,
    name: "Adidas Stan Smith",
    category: "adidas",
    price: 2300000,
    image: "./assets/images/adidas/4.png",
  },
  {
    id: 15,
    name: "Adidas Superstar",
    category: "adidas",
    price: 2400000,
    image: "./assets/images/adidas/5.png",
  },
  {
    id: 16,
    name: "Adidas NMD R1",
    category: "adidas",
    price: 3200000,
    image: "./assets/images/adidas/6.png",
  },
  {
    id: 17,
    name: "Adidas Yeezy Boost 350",
    category: "adidas",
    price: 8500000,
    image: "./assets/images/adidas/7.png",
  },
  {
    id: 18,
    name: "Adidas Campus 00s",
    category: "adidas",
    price: 2600000,
    image: "./assets/images/adidas/8.png",
  },
  {
    id: 19,
    name: "Adidas Gazelle",
    category: "adidas",
    price: 2500000,
    image: "./assets/images/adidas/9.png",
  },
  {
    id: 20,
    name: "Adidas Ultraboost Light",
    category: "adidas",
    price: 4100000,
    image: "./assets/images/adidas/10.png",
  },

  /* ================== PHỤ KIỆN GIÀY (10) ================== */
  {
    id: 21,
    name: "Tất Nike Everyday Cushion",
    category: "phukien",
    price: 350000,
    image: "./assets/images/accessory/1.png",
  },
  {
    id: 22,
    name: "Tất Adidas Performance Crew",
    category: "phukien",
    price: 320000,
    image: "./assets/images/accessory/2.png",
  },
  {
    id: 23,
    name: "Bộ vệ sinh giày Nike",
    category: "phukien",
    price: 450000,
    image: "./assets/images/accessory/3.png",
  },
  {
    id: 24,
    name: "Dung dịch vệ sinh giày Jason Markk",
    category: "phukien",
    price: 650000,
    image: "./assets/images/accessory/4.png",
  },
  {
    id: 25,
    name: "Xịt khử mùi giày Adidas",
    category: "phukien",
    price: 280000,
    image: "./assets/images/accessory/5.png",
  },
  {
    id: 26,
    name: "Túi đựng giày Nike Training",
    category: "phukien",
    price: 520000,
    image: "./assets/images/accessory/6.png",
  },
  {
    id: 27,
    name: "Túi đựng giày Adidas Originals",
    category: "phukien",
    price: 480000,
    image: "./assets/images/accessory/7.png",
  },
  {
    id: 28,
    name: "Miếng chống gãy mũi giày Sneaker Shield",
    category: "phukien",
    price: 300000,
    image: "./assets/images/accessory/8.png",
  },
  {
    id: 29,
    name: "Dây giày thun không cần buộc",
    category: "phukien",
    price: 180000,
    image: "./assets/images/accessory/9.png",
  },
  {
    id: 30,
    name: "Xịt chống nước giày Crep Protect",
    category: "phukien",
    price: 550000,
    image: "./assets/images/accessory/10.png",
  },
];
